### ISSUE TITLE
incorrect assumption in examples

### ISSUE THREAD

**Issue by majestrate** [MuxZeroNet/leaflet#1]
https://github.com/MuxZeroNet/leaflet/blob/4f573a5d93cce48a1e05e06cec069b863e3d94ac/leaflet/examples/basic.py#L25

this operation is not optional with i2pd, sam only accepts long form addresses on connect.

**Comment by MuxZeroNet** [comment]
The NS lookup will be performed for you by the `our_dest.connect(...)` API if you give it a string. It's very intuitive, isn't it?

https://github.com/MuxZeroNet/leaflet/blob/4708fa5c3c83a3a042794d091af9c3c98aa3515f/leaflet/control.py#L105-L109

**Comment by majestrate** [comment]
ah i see, that's kinda screwy but okay.
